##############################################################################
#
# Example properties file
#
##############################################################################
# Environment
mondrian.catalogURL=file://c:/Tomcat9/webapps/emondrian/WEB-INF/schema/oper_mondrian.xml 

# mysql
mondrian.test.jdbcURL=Jdbc=jdbc:clickhouse://bi-ch01.loymax.local:8123/amwine_loymaxdw_dm?user=default;socket_timeout=300000;JdbcTimeout= 300000;jdbc.maxIdle=200;jdbc.maxTotal=200
# to specify the jdbc username and password:
# mondrian.test.jdbcUser=foodmart
# mondrian.test.jdbcPassword=foodmart
mondrian.jdbcDrivers=com.clickhouse.jdbc.ClickHouseDriver

# Use MD5 based caching for the RolapSchema instance
mondrian.catalog.content.cache.enabled=true

# both read and use aggregate tables
mondrian.rolap.aggregates.Use=true
mondrian.rolap.aggregates.Read=true

# generate aggregate sql (for every mdx query)
#mondrian.rolap.aggregates.generateSql=true

# pretty print sql (if log level for mondrian.rolap.RolapUtil is DEBUG)
mondrian.rolap.generate.formatted.sql=true

# by default the aggregate table with the smallest number of rows
# (rather than rows times size of each row) is used
#mondrian.rolap.aggregates.ChooseByVolume=true